export default [
  {
      id: 1,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'to do',
      level: 'P',
  },
  {
      id: 2,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'doing',
      level: 'P',
  },
  {
      id: 3,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'done',
      level: 'P',
  },
  {
      id: 4,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'to do',
      level: 'P',
  },
  {
      id: 5,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'to do',
      level: 'P',
  },
  {
      id: 6,
      title: 'asd',
      description: 'what the hell is going on?',
      teacher: 'life',
      discipline: 'como quebrar a cara',
      due_date: '23 de nunca de 2050',
      state: 'to do',
      level: 'P',
  }
]